import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { dbConnect } from "@/utils/db" // Adjust the path to your dbConnect function
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // Connect to the MongoDB database when the component mounts
  const connectToDatabase = async () => {
    try {
      await dbConnect()
      console.log("Connected to the database")
    } catch (error) {
      console.error("Error connecting to the database:", error)
    }
  }

  connectToDatabase()

  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
